# Generated by Django 6.0.2 on 2026-02-25 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id_primary', models.BigAutoField(primary_key=True, serialize=False)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('pfp', models.URLField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('taskID', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('remindAt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.profile')),
            ],
        ),
    ]
