# Generated by Django 6.0.2 on 2026-02-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='users',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
