# Generated by Django 6.0.2 on 2026-03-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_profile_table_alter_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
