# Generated by Django 6.0.4 on 2026-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
